# Generated by Django 4.2.1 on 2023-06-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('Apellido', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
